server:
  port: 9090

spring:
  application:
    name: orders-management-system

  datasource:
    url: jdbc:mysql://localhost:3306/Company_SD
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create

    show-sql: true

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

        jdbc:
          time_zone: UTC

logging:
  level:
    org.hibernate.SQL: DEBUG

my:
  app:
    deptName: it
    deptNum: 20

application:
  security:
    jwt:
      secret-key: 6L9bZzFI6b93aYd6R3qL2tpUSfJHEJ16NpQ92Bwl6yU=